# baseURL
@baseURL = http://localhost:4000

###
# Get All Policies
GET {{ baseURL }}/api/v1/policies

###
# Get Policy By Client Name
POST {{ baseURL }}/api/v1/policies/query?clientName=Manning


###
# Get Client By Policy Number
POST {{baseURL}}/api/v1/policies/search?policyId=0d4bc5cf-4677-4876-bad3-c7064ebaf3b2git 