# baseURL
@baseURL = http://localhost:4000

###
# Get All Policies
GET {{ baseURL }}/api/v1/policies

###
# Get Policy By Client Name
POST {{ baseURL }}/api/v1/policies/query?clientName=Manning


###
# Get Client By Policy Number
POST {{baseURL}}/api/v1/policies/search?policyId=5a72ae47-d077-4f74-9166-56a6577e31b9